-- Setup Snowflake objects for dbt using key-pair authentication.
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE DBT_WH
  WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = FALSE;

CREATE OR REPLACE DATABASE DBT_DEV_DB;

CREATE OR REPLACE ROLE DBT_ROLE;

CREATE OR REPLACE SCHEMA DBT_DEV_DB.JM;

CREATE OR REPLACE USER DBT_USER
  TYPE = SERVICE
  DEFAULT_WAREHOUSE = DBT_WH
  DEFAULT_ROLE = DBT_ROLE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhY7v3Fg0qL3CE0fTy2YXT0rUehGhMB4zfuo7/mlJ3W9vA4S6db4PZY+3dACLsLRcyVYeftzi0pqktNXerGhLEbH7ltEO/WGZUuPLrpNRbI6y1EPup4q1xEUC+8WT5xqCCTeOq++vZ75gW9UGJCW+3DDAfWTpaEkJCQGicIyawDEcenpVTwIFCMk75RDmwyB/PXWUzTytFczd/PE/UR7FwLYr+TdqWjCAkdGDgUCLxKt9nJyE9bWyz70cZ4avxgxVA+fabHgaRUu0HwVcALzF/MHeRa6zOQgFUl1CkygMMzT44vdqC+ZM6sVfEvhSOK1c6Tlktq/cqy+U/uDQ2BgwOwIDAQAB';

GRANT ROLE DBT_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_ROLE TO USER DBT_USER;

GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
GRANT MONITOR ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;

GRANT USAGE ON DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA DBT_DEV_DB.JM TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DBT_DEV_DB.JM TO ROLE DBT_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;

GRANT SELECT ON ALL TABLES IN DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DBT_DEV_DB TO ROLE DBT_ROLE;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE DBT_ROLE;

SHOW GRANTS TO USER DBT_USER;
SHOW GRANTS TO ROLE DBT_ROLE;
DESC USER DBT_USER;
